### PR TITLE
Create billboard.yml v0.1

### PR DESCRIPTION
**Pull request by pdfext**
A profil to declare advertising billboards

### CODE REVIEW

**Comment by loicortola** [comment]
Mmmmh, lots of spec mistakes in that one:

Please take a look at the following stack to find your errors.
I will walk you through the first one to help you understand how to debug:

```js
{
    property: 'instance.groups[0].items[0].tags[2]',
    message: 'is not exactly one from </TagStringValues>,</TagConstant>',
    schema: '/Tag',
    instance:
     { description: [Object],
       key: 'support',
       required: false,
       type: 'SINGLE_CHOICE',
       values: [Object] },
    name: 'oneOf',
    argument: [ '</TagStringValues>', '</TagConstant>' ],
    stack: 'instance.groups[0].items[0].tags[2] is not exactly one from </TagStringValues>,</TagConstant>' 
}
```

instance.groups[0].items[0].tags[2] refers to the third tag of the first item of the first group (indexes are 0-based).
This corresponds to the following tag:

```yml
 - 
            description: 
              default: "Par quoi est supporté le panneau  ?"
              en: "What does support the billboard ?"
              fr: "Par quoi est supporté le panneau ?"
            key: support
            required: false
            type: SINGLE_CHOICE
            values: 
              - 
                default: "Tronc scellé au sol"
                en: "Grounded trunk"
                fr: "Tronc scellé au sol"
                trunk: ~
              - 
                default: "Pylônes scellés au sol"
                en: "Grounded poles"
                fr: "Pylônes scellés au sol"
                poles: ~
              - 
                default: "Panneau mural"
                en: "Wall billboard"
                fr: "Panneau mural"
                wall: ~
```
Indeed, the values are not formatted according to the spec. See $.groups.$.items.$.tags.$.values in spec.


Here is the full error-trace of your file:

```
File billboard.yml is invalid. Will be ignored in parsing.
[ ValidationError {
    property: 'instance.groups[0].items[0].tags[2]',
    message: 'is not exactly one from </TagStringValues>,</TagConstant>',
    schema: '/Tag',
    instance:
     { description: [Object],
       key: 'support',
       required: false,
       type: 'SINGLE_CHOICE',
       values: [Object] },
    name: 'oneOf',
    argument: [ '</TagStringValues>', '</TagConstant>' ],
    stack: 'instance.groups[0].items[0].tags[2] is not exactly one from </TagStringValues>,</TagConstant>' },
  ValidationError {
    property: 'instance.groups[0].items[0].tags[3]',
    message: 'is not exactly one from </TagStringValues>,</TagConstant>',
    schema: '/Tag',
    instance:
     { description: [Object],
       key: 'type',
       required: false,
       type: 'SINGLE_CHOICE',
       values: [Object] },
    name: 'oneOf',
    argument: [ '</TagStringValues>', '</TagConstant>' ],
    stack: 'instance.groups[0].items[0].tags[3] is not exactly one from </TagStringValues>,</TagConstant>' },
  ValidationError {
    property: 'instance.groups[0].items[0].tags[4]',
    message: 'is not exactly one from </TagStringValues>,</TagConstant>',
    schema: '/Tag',
    instance:
     { description: [Object],
       key: 'display_surface',
       required: false,
       type: 'SINGLE_CHOICE',
       values: [Object] },
    name: 'oneOf',
    argument: [ '</TagStringValues>', '</TagConstant>' ],
    stack: 'instance.groups[0].items[0].tags[4] is not exactly one from </TagStringValues>,</TagConstant>' },
  ValidationError {
    property: 'instance.groups[0].items[0].tags[5]',
    message: 'is not exactly one from </TagStringValues>,</TagConstant>',
    schema: '/Tag',
    instance:
     { description: [Object],
       key: 'operator',
       required: false,
       type: 'SINGLE_CHOICE',
       values: [Object] },
    name: 'oneOf',
    argument: [ '</TagStringValues>', '</TagConstant>' ],
    stack: 'instance.groups[0].items[0].tags[5] is not exactly one from </TagStringValues>,</TagConstant>' },
  ValidationError {
    property: 'instance.groups[0].items[0].tags[6]',
    message: 'is not exactly one from </TagStringValues>,</TagConstant>',
    schema: '/Tag',
    instance:
     { description: [Object],
       key: 'land_property',
       required: false,
       type: 'SINGLE_CHOICE',
       values: [Object] },
    name: 'oneOf',
    argument: [ '</TagStringValues>', '</TagConstant>' ],
    stack: 'instance.groups[0].items[0].tags[6] is not exactly one from </TagStringValues>,</TagConstant>' },
  ValidationError {
    property: 'instance.groups[0].items[0].tags[7]',
    message: 'is not exactly one from </TagStringValues>,</TagConstant>',
    schema: '/Tag',
    instance:
     { description: [Object],
       key: 'message',
       required: true,
       type: 'SINGLE_CHOICE',
       values: [Object] },
    name: 'oneOf',
    argument: [ '</TagStringValues>', '</TagConstant>' ],
    stack: 'instance.groups[0].items[0].tags[7] is not exactly one from </TagStringValues>,</TagConstant>' },
  ValidationError {
    property: 'instance.groups[0].items[0].tags[8]',
    message: 'is not exactly one from </TagStringValues>,</TagConstant>',
    schema: '/Tag',
    instance:
     { description: [Object],
       key: 'lit',
       required: true,
       type: 'SINGLE_CHOICE',
       values: [Object] },
    name: 'oneOf',
    argument: [ '</TagStringValues>', '</TagConstant>' ],
    stack: 'instance.groups[0].items[0].tags[8] is not exactly one from </TagStringValues>,</TagConstant>' },
  ValidationError {
    property: 'instance.groups[0].items[0].constraints[2].condition',
    message: 'is not exactly one from </ConditionExists>,</ConditionEquals>',
    schema: '/Condition',
    instance: { type: 'EQUALS', value: 4 },
    name: 'oneOf',
    argument: [ '</ConditionExists>', '</ConditionEquals>' ],
    stack: 'instance.groups[0].items[0].constraints[2].condition is not exactly one from </ConditionExists>,</ConditionEquals>' },
  ValidationError {
    property: 'instance.groups[0].items[0].constraints[3].condition',
    message: 'is not exactly one from </ConditionExists>,</ConditionEquals>',
    schema: '/Condition',
    instance: { type: 'EQUALS', value: 84 },
    name: 'oneOf',
    argument: [ '</ConditionExists>', '</ConditionEquals>' ],
    stack: 'instance.groups[0].items[0].constraints[3].condition is not exactly one from </ConditionExists>,</ConditionEquals>' },
  ValidationError {
    property: 'instance.groups[0].items[0].constraints[4].condition',
    message: 'is not exactly one from </ConditionExists>,</ConditionEquals>',
    schema: '/Condition',
    instance: { type: 'EQUALS', value: 12 },
    name: 'oneOf',
    argument: [ '</ConditionExists>', '</ConditionEquals>' ],
    stack: 'instance.groups[0].items[0].constraints[4].condition is not exactly one from </ConditionExists>,</ConditionEquals>' } ]
```


Good luck :)

**Comment by pdfext** [comment]
Yes what i didn't pay attention to is that when I passed my .yml through http://www.yamllint.com/, I didn't notice that it scrambled my file. For example the following sequence : 
 _values:
              - trunk :
                default: Tronc scellé au sol
                fr: Tronc scellé au sol
                en: Grounded trunk
              - poles :
                default: Pylônes scellés au sol
                fr: Pylônes scellés au sol
                en: Grounded poles
              - wall :
                default: Panneau mural
                fr: Panneau mural
                en: Wall billboard_

was automatically changed into : 

_values: 
              - 
                default: "Tronc scellé au sol"
                en: "Grounded trunk"
                fr: "Tronc scellé au sol"
                trunk: ~
              - 
                default: "Pylônes scellés au sol"
                en: "Grounded poles"
                fr: "Pylônes scellés au sol"
                poles: ~
              - 
                default: "Panneau mural"
                en: "Wall billboard"
                fr: "Panneau mural"
                wall: ~_

I believe this is the reason of the error.
Don't you think so ?
Thanks

**Comment by loicortola** [comment]
Looks like it may be the source yes.
Try to send the original file or another linter and see what it does?

**Comment by loicortola** [comment]
@pdfext any news on that one?

**Pull request closed without merging**
